/*
 * Problem: 389. Find the Difference
 * 
 * Description:
 * You are given two strings s and t. String t is generated by random shuffling string s and
 * then adding one more letter at a random position. Return the letter that was added to t.
 * 
 * Requirements:
 * - Find the extra letter added to t
 * - String t is s shuffled with one extra letter
 * - Return the added character
 * 
 * Example:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * 
 * Constraints:
 * - 0 <= s.length <= 1000
 * - t.length == s.length + 1
 * - s and t consist of lowercase English letters
 */

class Solution {
    public char findTheDifference(String s, String t) {
        int total = t.charAt(s.length());
        for (int i = 0; i < s.length(); i++)
            total += (t.charAt(i) - s.charAt(i));
        return (char) total;
    }

    /* public char findTheDifference(String s, String t) {
        int total = t.charAt(s.length());
        for (int i = 0; i < s.length(); i++) {
            total ^= t.charAt(i);
            total ^= s.charAt(i);
        }
        return (char) total;
    } */
}
